---
title: Download species vulnerability traits and scores
author: "Casey O'Hara"
format:
  html:
    embed-resources: true
---

## Summary

Download species vulnerability framework traits and scores from KNB, saved to `_data/ohara_2024/`. These data underpin the trait-based vulnerability framework originally described in Butt et al. (2022) and updated in O'Hara et al. (2024).
* Butt, N., et al. (2022). A trait-based framework for assessing the vulnerability of marine species to human impacts. *Ecosphere*, 13(2), e3919. https://doi.org/10.1002/ecs2.3919
* O'Hara, C. C., et al. (2024). Cumulative human impacts on global marine fauna highlight risk to biological and functional diversity. *PLOS ONE*, 19(9), e0309788. https://doi.org/10.1371/journal.pone.0309788

Data are hosted at https://knb.ecoinformatics.org/view/doi:10.5063/F1QC0211:

* [`spp_vuln_framework_traits.zip`](https://knb.ecoinformatics.org/knb/d1/mn/v2/object/urn%3Auuid%3Ab04c2ef1-7e75-4cd7-977f-56710fc57a9c) — per-species vulnerability trait values
* [`spp_vuln_framework_scores.zip`](https://knb.ecoinformatics.org/knb/d1/mn/v2/object/urn%3Auuid%3A614cd599-78eb-4e6b-905e-e68a2b2a0489) — aggregated vulnerability scores per species and stressor


## Methods

Check for existence in the `data` folder, and if necessary, download/unzip.

Make sure to manually add these to .gitignore!

### Download traits data


